secoverview/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

urlpatterns = [
    path('token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('ransomwarelive/groups/fetch', views.fetch_groups, name='ransomware_fetch_groups'),
    path('ransomwarelive/victims/fetch', views.fetch_victims, name='ransomware_fetch_victims'),
    path('rssapp/feeds/update', views.rss_feed_update, name='rss_feed_update'),
    path('nmap/scan', views.nmap_scan, name='nmap_scan'),
    path('mlnids/upload', views.mlnids_upload_csv, name='mlnids_upload_csv'),
    path('assets/gather/all', views.assets_gather_all, name='assets_gather_all'),
    path('cve/daily/get', views.cve_get_daily, name='cve_get_daily'),
    path('dns/enumerate', views.api_dns_enumerate, name='api_dns_enumerate'),
    path('web/crt/get', views.api_crtsh_get, name='api_crtsh_get'),
    path('web/webheaders/get', views.api_webheaders_get, name='api_webheaders_get'),
    path('web/webtechfingerprinting/get', views.api_webfingerprinting_get, name='api_webfingerprinting_get'),
    path('web/all/get', views.api_weball_get, name='api_weball_get'),
    path('ipcheck/check', views.api_ipcheck_get, name='api_ipcheck_get'),
    path('logout', views.logout_view, name='logout_api'),
]

secoverview/secoverview/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('assets/', include('assets.urls')),
    path('backup/', include('backup.urls')),
    path('ipcheck/', include('ipcheck.urls')),
    path('chat/', include('chat.urls')),
    path('cve/', include('cvedata.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dns/', include('dnsops.urls')),
    path('mlnids/', include('mlnids.urls')),
    path('nmap/', include('nmapapp.urls')),
    path('ransomwarelive/', include('ransomwarelive.urls')),
    path('rss/', include('rssapp.urls')),
    path('web/', include('webops.urls')),
    path('yara/', include('yarascan.urls')),
]

#if settings.DEBUG == True:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secoverview/webops/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.web_overview, name='web_overview'),
]

secoverview/webops/models.py
from django.db import models

class CRTSHScan(models.Model):
    domain = models.CharField(max_length=255)
    scaned_at = models.DateTimeField(auto_now_add=True)

class CRTSHResult(models.Model):
    domain = models.ForeignKey(CRTSHScan, on_delete=models.CASCADE)
    result = models.TextField(max_length=255)

class WebHeaderCheck(models.Model):
    domain = models.CharField(max_length=255)
    scaned_at = models.DateTimeField(auto_now_add=True)
    hsts_detected = models.BooleanField(default=False) 
    hsts_value = models.TextField(null=True, blank=True, default=None)
    hsts_issues = models.TextField(null=True, blank=True, default=None)
    xframeoptions_detected = models.BooleanField(default=False)
    xframeoptions_value = models.TextField(null=True, blank=True, default=None)
    xframeoptions_issues = models.TextField(null=True, blank=True, default=None)
    xcontenttypeoptions_detected = models.BooleanField(default=False)
    xcontenttypeoptions_value = models.TextField(null=True, blank=True, default=None)
    xcontenttypeoptions_issues = models.TextField(null=True, blank=True, default=None)
    csp_detected = models.BooleanField(default=False)
    csp_value = models.TextField(null=True, blank=True, default=None)
    csp_issues = models.TextField(null=True, blank=True, default=None)
    refferrerpolicy_detected = models.BooleanField(default=False)
    refferrerpolicy_value = models.TextField(null=True, blank=True, default=None)
    refferrerpolicy_issues = models.TextField(null=True, blank=True, default=None)
    xssprotection_detected = models.BooleanField(default=False)
    xssprotection_value = models.TextField(null=True, blank=True, default=None)
    xssprotection_issues = models.TextField(null=True, blank=True, default=None)
    permissionspolicy_detected = models.BooleanField(default=False)
    permissionspolicy_value = models.TextField(null=True, blank=True, default=None)
    permissionspolicy_issues = models.TextField(null=True, blank=True, default=None)
    clearsite_detected = models.BooleanField(default=False)
    clearsite_value = models.TextField(null=True, blank=True, default=None)
    clearsite_issues = models.TextField(null=True, blank=True, default=None)
    crossoriginopenerpolicy_detected = models.BooleanField(default=False)
    crossoriginopenerpolicy_value = models.TextField(null=True, blank=True, default=None)
    crossoriginopenerpolicy_issues = models.TextField(null=True, blank=True, default=None)
    crossoriginembedderpolicy_detected = models.BooleanField(default=False)
    crossoriginembedderpolicy_value = models.TextField(null=True, blank=True, default=None)
    crossoriginembedderpolicy_issues = models.TextField(null=True, blank=True, default=None)
    
class WebTechFingerprinting_Scan(models.Model):
    domain = models.CharField(max_length=255)
    scaned_at = models.DateTimeField(auto_now_add=True)

class WebTechFingerprinting_Results(models.Model):
    domain = models.ForeignKey(WebTechFingerprinting_Scan, on_delete=models.CASCADE)
    technologie = models.CharField(max_length=100)
    version = models.TextField(null=True, blank=True, default=None)

secoverview/webops/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .webops.web_headers import check_security_headers
from .webops.crt_sh_ops import query_crtsh
from .webops.web_tech_fingerprinting import analyze_technologies
from .models import CRTSHResult, WebTechFingerprinting_Results

@login_required
def web_overview(request):
    """View to display RSS feed data"""
    assert isinstance(request, HttpRequest)
    if request.method == 'POST':
        domain = request.POST.get('domain')
        headers = check_security_headers(domain)
        crt_result = CRTSHResult.objects.filter(domain=query_crtsh(domain))
        webtechfingerprint = WebTechFingerprinting_Results.objects.filter(domain=analyze_technologies(domain))
        return render(
            request, 
            "web_overview.html", 
            {
                'title':'Web Ops Overview',
                'year':datetime.now().year,
                'domain':domain, 
                'webheaders':headers,
                'crt_result':crt_result,
                'webtechfingerprint':webtechfingerprint,
                'chatcontext':f"This page show the following data: {domain} - {headers} - {crt_result} - {webtechfingerprint} "
            })
    else:
        return render(
            request, 
            "web_overview.html", 
            {
                'title':'Web Ops Overview',
                'year':datetime.now().year,
                'domain':None,
                'webheaders':None,
                'crt_scan_result':None,
                'webtechfingerprint':None,
                'chatcontext':"This page allows to querry a domain for its web technologies, cert subdomains history and its http security headers."
            })

secoverview/webops/templates/web_overview.html
{% extends "layout.html" %}

{% block content %}
<br>
<h1>Web Ops</h1>
<div class="p-4">
    <form method="POST">
        {% csrf_token %}
        <label class="me-2" for="id_domain">Domain to check:</label>
        <input type="text" class="form-control" name="domain" id="id_domain" required><br><br>

        <button type="submit" class="btn btn-dark">Check</button>
    </form>
    <br>
    {% if domain %}
    <div class="d-grid gap-4 d-md-flex">
        <h5><b>Domain:</b> {{ domain }}</h5>
        <form action="{% url 'nmapscan' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" class="form-control" name="ip" id="id_IP_dst" value="{{ response.ip }}">
            <input type="hidden" class="form-control" name="parameters" id="id_parameters" value="-sV -n -R -p 1-1024">
            <button type="submit" class="btn btn-dark">Scan with NMAP</button>
        </form>
    </div>
    <br>
    {% endif %}
    {% if webheaders %}
    <h5><b>Scan Date:</b> {{ webheaders.scaned_at }}</h5>
    <h5><b>Headers</b></h5>
    <table class="table table-hover">
        <tr>
            <td><b>Header</b></td>
            <td><b>Detected</b></td>
            <td><b>Value</b></td>
            <td><b>Issue</b></td>
        </tr>
        <tr>
            <td>Strict-Transport-Security (HSTS)</td>
            <td>{{ webheaders.hsts_detected }}</td>
            <td>{{ webheaders.hsts_value }}</td>
            <td>{{ webheaders.hsts_issues }}</td>
        </tr>
        <tr>
            <td>X-Frame-Options</td>
            <td>{{ webheaders.xframeoptions_detected }}</td>
            <td>{{ webheaders.xframeoptions_value }}</td>
            <td>{{ webheaders.xframeoptions_issues }}</td>
        </tr>
        <tr>
            <td>X-Content-Type-Options</td>
            <td>{{ webheaders.xcontenttypeoptions_detected }}</td>
            <td>{{ webheaders.xcontenttypeoptions_value }}</td>
            <td>{{ webheaders.xcontenttypeoptions_issues }}</td>
        </tr>
        <tr>
            <td>Content-Security-Policy (CSP)</td>
            <td>{{ webheaders.csp_detected }}</td>
            <td>{{ webheaders.csp_value }}</td>
            <td>{{ webheaders.csp_issues }}</td>
        </tr>
        <tr>
            <td>Referrer-Policy</td>
            <td>{{ webheaders.refferrerpolicy_detected }}</td>
            <td>{{ webheaders.refferrerpolicy_value }}</td>
            <td>{{ webheaders.refferrerpolicy_issues }}</td>
        </tr>
        <tr>
            <td>X-XSS-Protection</td>
            <td>{{ webheaders.xssprotection_detected }}</td>
            <td>{{ webheaders.xssprotection_value }}</td>
            <td>{{ webheaders.xssprotection_issues }}</td>
        </tr>
        <tr>
            <td>Permissions-Policy</td>
            <td>{{ webheaders.permissionspolicy_detected }}</td>
            <td>{{ webheaders.permissionspolicy_value }}</td>
            <td>{{ webheaders.permissionspolicy_issues }}</td>
        </tr>
        <tr>
            <td>Clear-Site-Data</td>
            <td>{{ webheaders.clearsite_detected }}</td>
            <td>{{ webheaders.clearsite_value }}</td>
            <td>{{ webheaders.clearsite_issues }}</td>
        </tr>
        <tr>
            <td>Cross-Origin-Opener-Policy (COOP)</td>
            <td>{{ webheaders.crossoriginopenerpolicy_detected }}</td>
            <td>{{ webheaders.crossoriginopenerpolicy_value }}</td>
            <td>{{ webheaders.crossoriginopenerpolicy_issues }}</td>
        </tr>
        <tr>
            <td>Cross-Origin-Embedder-Policy (COEP)</td>
            <td>{{ webheaders.crossoriginembedderpolicy_detected }}</td>
            <td>{{ webheaders.crossoriginembedderpolicy_value }}</td>
            <td>{{ webheaders.crossoriginembedderpolicy_issues }}</td>
        </tr>
    </table>
    <br>
    {% endif %}

    {% if crt_result %}
    <h1>Crtsh Result</h1>
    <table class="table table-hover">
        <tr>
            <td><b>Result</b></td>
        </tr>
        {% for result in crt_result %}
        <tr>
            <td>{{ result.result }}</td>
        </tr>
        {% endfor %}
    </table>
    <br>
    {% endif %}

    {% if webtechfingerprint %}
    <h1>Web Tech Fingerprinting Result</h1>
    <table class="table table-hover">
        <tr>
            <td><b>Technologie</b></td>
            <td><b>Version</b></td>
            <td><b>Actions</b></td>
        </tr>
        {% for result in webtechfingerprint %}
        <tr>
            <td>{{ result.technologie }}</td>
            <td>{{ result.version }}</td>
            <td><a href="{% url 'cve_view' %}?search={{ result.technologie }}" class="btn btn-dark">Search CVE</a></td>
        </tr>
        {% endfor %}
    </table>
    <br>
    {% endif %}
</div>


{% endblock %}